### ISSUE TITLE
luarocks(1) unable to find fbtorch

### ISSUE THREAD

**Issue by pyk** [facebook/fbtorch#5]
```
$ luarocks install fbtorch

Error: No results matching query were found.
```

Or via [LuaRocks site search](https://luarocks.org/search?q=fbtorch)

**Comment by pyk** [comment]
my current solution is uploading the rockfile manually and running the following command:

```
luarocks install --server=http://luarocks.org/manifests/pyk fbtorch
```

**Comment by loveJasmine** [comment]
luarocks install --server=http://luarocks.org/manifests/pyk fbtorch
Installing http://luarocks.org/manifests/pyk/fbtorch-scm-1.rockspec...
Using http://luarocks.org/manifests/pyk/fbtorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'fbtorch'...
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 17 (delta 2), reused 12 (delta 2), pack-reused 0
Receiving objects: 100% (17/17), 7.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2/2), done.
   git submodule init
   git submodule update
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/Users/yike.ke/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/Users/yike.ke/torch/install/lib/luarocks/rocks/fbtorch/scm-1"

fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- The C compiler identification is AppleClang 8.1.0.8020038
-- The CXX compiler identification is AppleClang 8.1.0.8020038
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- FBCUNN Untested/Unsupported on OSX
-- Found Torch7 in /Users/yike.ke/torch/install
CMake Error at /Library/Python/2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  REQUIRED_ARGS (missing: FOLLY_INCLUDE_DIR FOLLY_LIBRARIES)
Call Stack (most recent call first):
  /Library/Python/2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFolly.cmake:23 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:12 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_fbtorch-scm-1-3933/fbtorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.
ali-186590cc37a5:byteNet-tensorflow yike.ke$

**Comment by guotong1988** [comment]
same error.

**Comment by pyk** [comment]
@loveJasmine @guotong1988 you can use this:

```
luarocks install https://raw.githubusercontent.com/facebook/fbtorch/master/rocks/fbtorch-scm-1.rockspec
```

**Comment by rivaldinho** [comment]
@pyk 
use luarocks install https://raw.githubusercontent.com/facebook/fbtorch/master/rocks/fbtorch-scm-1.rockspec
still same error
